// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OurFirstSolution.Mvc.Api.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ContactMeViewModel
    {
        /// <summary>
        /// Initializes a new instance of the ContactMeViewModel class.
        /// </summary>
        public ContactMeViewModel() { }

        /// <summary>
        /// Initializes a new instance of the ContactMeViewModel class.
        /// </summary>
        public ContactMeViewModel(string fromEmail, string subject, string message)
        {
            FromEmail = fromEmail;
            Subject = subject;
            Message = message;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FromEmail")]
        public string FromEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Subject")]
        public string Subject { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (FromEmail == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FromEmail");
            }
            if (Subject == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Subject");
            }
            if (Message == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Message");
            }
        }
    }
}
